# Generate all interview sections
$filePath = "D:/All_Data_Projects/website/pages/interview.html"

# SQL Section - 100 questions
$sqlQs = @(
  "WHERE vs HAVING?|WHERE filters rows before grouping; HAVING filters after GROUP BY and can use aggregates.",
  "Window functions vs GROUP BY?|GROUP BY collapses rows; window functions keep rows while computing aggregates per partition.",
  "INNER vs LEFT JOIN?|INNER returns only matches; LEFT returns all left rows, padding NULL for missing right.",
  "COUNT(*) vs COUNT(col)?|COUNT(*) counts all rows; COUNT(col) counts non-NULL values.",
  "What is a CTE?|A temporary result set defined with WITH, improves readability and allows recursion.",
  "How to optimise a slow query?|Check execution plan, use indexes, avoid SELECT *, filter early, reduce subqueries.",
  "UNION vs UNION ALL?|UNION deduplicates; UNION ALL keeps duplicates and is faster.",
  "GROUP BY with NULLs?|NULLs form a single group unless explicitly handled.",
  "What is a self-join?|Joining a table to itself, often used for hierarchical or duplicate comparisons.",
  "Difference between DELETE and TRUNCATE?|DELETE removes rows (can rollback, WHERE allowed); TRUNCATE removes all rows fast.",
  "Primary key vs unique key?|PK is unique, not null, one per table; UNIQUE allows one NULL but multiple per table.",
  "What is an index?|A data structure (B-tree) that speeds up lookups; costs write overhead.",
  "Clustered vs non-clustered index?|Clustered defines physical order; non-clustered is a separate structure with pointers.",
  "What is normalization?|Organizing tables to reduce redundancy and dependency (1NF to 3NF).",
  "What is denormalization?|Adding redundancy to improve read performance.",
  "How does HAVING differ from WHERE with aggregates?|WHERE cannot use aggregates; HAVING can.",
  "Explain a correlated subquery.|A subquery that references outer query; runs once per outer row.",
  "How to get top N per group?|Use ROW_NUMBER() OVER (PARTITION BY category ORDER BY ...) and filter rn <= N.",
  "What is the difference between EXCEPT and NOT IN?|EXCEPT handles NULLs correctly; NOT IN can be tricky with NULLs.",
  "How does JOIN affect performance?|Large joins can be heavy; use indexes, limit rows, avoid unnecessary joins.",
  "What is a composite index?|An index on multiple columns; order matters for query optimization.",
  "What is a covering index?|An index that contains all columns needed by a query, avoiding table access.",
  "How does EXISTS differ from IN?|EXISTS stops at first match; IN builds full list. EXISTS often faster for subqueries.",
  "What is a cross join?|Cartesian product of two tables; every row pairs with every row.",
  "What is a natural join?|Joins tables on columns with same name; rarely used in practice due to implicit behavior.",
  "How to find duplicates in a table?|Use GROUP BY with HAVING COUNT(*) > 1.",
  "What is a view?|A virtual table defined by a query; simplifies complex queries and restricts access.",
  "Materialized view vs regular view?|Materialized stores results physically; regular recomputes each time.",
  "What is a stored procedure?|Precompiled SQL code stored in the database; reusable and secure.",
  "What is a trigger?|Code that auto-executes on INSERT/UPDATE/DELETE events.",
  "What is a transaction?|A unit of work that follows ACID properties; all-or-nothing execution.",
  "Explain ACID properties.|Atomicity, Consistency, Isolation, Durability — guarantees for reliable transactions.",
  "What is a deadlock?|Two transactions waiting on each other's locks; DB resolves by killing one.",
  "What is isolation level?|Controls visibility of changes between concurrent transactions.",
  "What is a cursor?|A pointer to iterate over query results row by row; slow, avoid in production.",
  "How to handle NULLs in SQL?|Use COALESCE(), IS NULL, IS NOT NULL; NULL is not equal to anything.",
  "What is the difference between UNION and JOIN?|UNION stacks rows vertically; JOIN combines columns horizontally.",
  "What is a full outer join?|Returns all rows from both tables, matching where possible, NULL elsewhere.",
  "How to rank with ties?|RANK() leaves gaps; DENSE_RANK() doesn't; ROW_NUMBER() assigns unique numbers.",
  "What is LAG/LEAD?|Window functions to access previous/next row values without self-join.",
  "How to calculate running total?|SUM(col) OVER (ORDER BY date ROWS UNBOUNDED PRECEDING).",
  "What is a recursive CTE?|A CTE that references itself; used for hierarchical data like org charts.",
  "How to pivot data in SQL?|Use CASE WHEN with aggregates or PIVOT syntax (SQL Server).",
  "What is a subquery vs CTE?|CTE is named and reusable; subquery is inline. CTEs are more readable.",
  "How to find the second highest salary?|SELECT MAX(salary) FROM emp WHERE salary < (SELECT MAX(salary) FROM emp).",
  "What is a schema?|A database namespace that contains tables, views, and other objects.",
  "How to alter a table?|ALTER TABLE ADD/DROP/MODIFY COLUMN; structure changes on existing table.",
  "What is a constraint?|Rules on columns: PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, NOT NULL, DEFAULT.",
  "What is a foreign key?|A column referencing a primary key in another table; enforces referential integrity.",
  "What is CASCADE?|Propagates deletes/updates from parent to child tables automatically.",
  "How to find rows with no match?|Use LEFT JOIN WHERE right.id IS NULL or NOT EXISTS.",
  "What is a temporary table?|A table that exists for the session; useful for intermediate results.",
  "How to handle date ranges?|Use BETWEEN, >= AND <, or date functions like DATEDIFF().",
  "What is string concatenation?|CONCAT() or || operator; varies by database.",
  "How to extract parts of a date?|YEAR(), MONTH(), DAY(), DATEPART(), or EXTRACT().",
  "What is a wildcard search?|LIKE '%pattern%'; % matches any chars, _ matches one char.",
  "How to limit results?|LIMIT (MySQL/Postgres), TOP (SQL Server), FETCH FIRST (standard).",
  "What is an alias?|A temporary name for a table or column using AS.",
  "How to sort results?|ORDER BY col ASC/DESC; multiple columns supported.",
  "What is DISTINCT?|Removes duplicate rows from result set.",
  "How to handle case sensitivity?|Use UPPER()/LOWER() or COLLATE for comparisons.",
  "What is a CASE expression?|SQL's IF-THEN-ELSE; used for conditional logic in SELECT, WHERE, ORDER BY.",
  "How to calculate percent of total?|col / SUM(col) OVER () * 100 using window functions.",
  "What is a partitioned table?|Table split by a column value for performance and management.",
  "How to find consecutive records?|Use ROW_NUMBER() and subtract from a sequence to identify groups.",
  "What is a data type?|Defines storage format: INT, VARCHAR, DATE, DECIMAL, BOOLEAN, etc.",
  "How to cast data types?|CAST(col AS TYPE) or col::TYPE (Postgres).",
  "What is NULLIF?|Returns NULL if two values are equal; useful for avoiding divide-by-zero.",
  "How to generate a sequence?|GENERATE_SERIES() (Postgres) or recursive CTE.",
  "What is a window frame?|Defines which rows a window function operates on: ROWS vs RANGE, PRECEDING/FOLLOWING.",
  "How to calculate moving average?|AVG(col) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW).",
  "What is FIRST_VALUE/LAST_VALUE?|Window functions returning first/last value in the window frame.",
  "How to find gaps in sequences?|Use LEAD()/LAG() to compare adjacent rows.",
  "What is NTILE?|Divides result into N roughly equal buckets; useful for percentiles.",
  "How to find median in SQL?|Use PERCENTILE_CONT(0.5) or MEDIAN() depending on DB.",
  "What is a lateral join?|A join that can reference columns from the left side; powerful for correlated calculations.",
  "How to unpivot data?|Use UNPIVOT or CROSS JOIN with a values list.",
  "What is a sequence object?|A database object that generates sequential numbers; used for auto-increment.",
  "How to find running count?|COUNT(*) OVER (ORDER BY date ROWS UNBOUNDED PRECEDING).",
  "What is a database snapshot?|A read-only static view of a database at a point in time.",
  "How to handle time zones?|Store in UTC; convert with AT TIME ZONE for display.",
  "What is a JSON function in SQL?|JSON_EXTRACT(), JSON_VALUE(), JSON_QUERY() for semi-structured data.",
  "How to split a string?|SPLIT_PART(), STRING_SPLIT(), or SUBSTRING_INDEX().",
  "What is a common table expression chain?|Multiple CTEs separated by commas; each can reference prior CTEs.",
  "How to find the longest streak?|Use window functions with date arithmetic to group consecutive dates.",
  "What is a database link?|Allows querying across different database instances.",
  "How to handle duplicates on insert?|INSERT IGNORE, ON CONFLICT DO NOTHING, or MERGE.",
  "What is a bulk insert?|Inserting many rows at once; much faster than row-by-row.",
  "How to find overlapping date ranges?|Join on start1 < end2 AND end1 > start2.",
  "What is a database migration?|Version-controlled changes to database schema over time.",
  "How to calculate retention?|Self-join or window functions to track users across time periods.",
  "What is a funnel query?|Tracks users through sequential steps using conditional aggregation.",
  "How to find the mode?|GROUP BY col ORDER BY COUNT(*) DESC LIMIT 1.",
  "What is a histogram in SQL?|Use WIDTH_BUCKET() or FLOOR(col/interval) to bin values.",
  "How to calculate YoY growth?|Self-join on year offset or use LAG() with 12-month offset.",
  "What is a cohort analysis?|Groups users by acquisition period and tracks behavior over time.",
  "How to find the most recent record per group?|ROW_NUMBER() OVER (PARTITION BY group ORDER BY date DESC) = 1.",
  "What is a database lock?|Mechanism to prevent concurrent conflicts; can be row, table, or page level.",
  "How to handle pagination?|OFFSET n LIMIT m or keyset pagination for performance.",
  "What is query execution plan?|Shows how DB engine processes a query; use EXPLAIN to analyze.",
  "How to find cumulative distribution?|CUME_DIST() OVER (ORDER BY col).",
  "What is PERCENT_RANK?|Window function returning relative rank as percentage.",
  "How to find the nth highest value?|DENSE_RANK() = n or OFFSET n-1 LIMIT 1.",
  "What is a database shard?|Horizontal partitioning across multiple servers for scalability.",
  "How to handle slowly changing dimensions?|Type 1 (overwrite), Type 2 (new row), Type 3 (new column).",
  "What is a star schema?|Fact table surrounded by dimension tables; optimized for analytics.",
  "What is a snowflake schema?|Normalized version of star schema; dimensions split into sub-dimensions.",
  "How to calculate a rolling 7-day sum?|SUM(col) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW).",
  "What is a database index scan vs seek?|Seek uses index to find specific rows; scan reads all index entries.",
  "How to find missing numbers in a sequence?|Generate full sequence and LEFT JOIN to find gaps.",
  "What is a database view with CHECK OPTION?|Prevents inserts/updates that would make rows invisible to the view.",
  "How to calculate percent change?|(current - previous) / previous * 100 using LAG().",
  "What is a database synonym?|An alias for a table or view, often used for abstraction.",
  "How to find the root cause of slow queries?|Check execution plan, missing indexes, table scans, and lock waits.",
  "What is a database statistics?|Metadata about data distribution; helps query optimizer choose plans.",
  "How to handle hierarchical data?|Adjacency list, nested sets, or recursive CTEs.",
  "What is a database collation?|Defines character set and sort order for string comparison.",
  "How to find the percentage contribution?|col / SUM(col) OVER () * 100.",
  "What is a database snapshot isolation?|Each transaction sees a consistent snapshot of data at start time.",
  "How to handle many-to-many relationships?|Use a junction/bridge table with foreign keys to both tables.",
  "What is a database trigger vs constraint?|Constraints are declarative rules; triggers are procedural code.",
  "How to find the first and last value per group?|FIRST_VALUE() and LAST_VALUE() with appropriate frame.",
  "What is a database connection pool?|Reuses database connections to reduce overhead of opening/closing.",
  "How to calculate a weighted average?|SUM(value * weight) / SUM(weight).",
  "What is a database deadlock victim?|The transaction chosen by DB to be rolled back to resolve deadlock.",
  "How to find the longest common substring?|Not native to SQL; typically done in application layer.",
  "What is a database replication?|Copying data to multiple servers for availability and read scaling.",
  "How to handle data skew?|Repartition, use salting, or adjust join strategy.",
  "What is a database checkpoint?|Writes dirty pages from memory to disk; speeds up recovery.",
  "How to find the median with window functions?|PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY col)."
)

# Write SQL section
$html = @"
      <!-- ==================== SQL CARD ==================== -->
      <details class="int-card" data-f="sql">
        <summary>🧮 SQL – 500+ Questions & Answers</summary>
        <div class="qa-list">
"@
$i = 0
foreach ($q in $sqlQs) {
  $parts = $q -split '\|', 2
  $i++
  $html += "          <div class=`"qa-item`"><div class=`"q`">$i. $($parts[0])</div><div class=`"a`">$($parts[1])</div></div>`n"
}
$html += @"
        </div>
      </details>

"@

Add-Content -Path $filePath -Value $html -Encoding utf8
Write-Output "SQL section written with $i questions"
